version: '3'

services:
  php-fpm:
    build:
      context: ./.misc/docker/php-fpm
    volumes:
      - ./src:/var/www
  nginx:
    build:
      context: ./.misc/docker/nginx
    volumes:
      - ./src:/var/www
      - ./.misc/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.misc/docker/nginx/sites/:/etc/nginx/sites-available
      - ./.misc/docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./.misc/docker/logs:/var/log
    depends_on:
      - php-fpm
    ports: [ 8000:8000 ]
  swagger_ui:
    image: swaggerapi/swagger-ui:latest
    ports: [ 8003:8080 ]
    volumes: [ ./.misc/openapi/openapi.v1.yaml:/app/openapi.v1.yaml ]
    environment:
      SWAGGER_JSON: /app/openapi.v1.yaml
  queue:
    image: rabbitmq:3.6-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: symfony
      RABBITMQ_DEFAULT_PASS: symfony
    ports:
      - 15672:15672
  mailhog:
    image: mailhog/mailhog:latest
    ports: [ 8002:8025 ]
    logging: { driver: none }

